# Generated by Django 3.2.5 on 2021-07-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20210701_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='images',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
