# Generated by Django 3.2.5 on 2021-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_measurement_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
